import { Station } from "@/types/route";

export const STATION_DISPLAY_NAME: Record<Station, string> = {
  sala: "Sala Phra Kieo",
  faculty_poli_sci: "Faculty of Political Science",
  faculty_econ: "Faculty of Economics",
  faculty_sci: "Faculty of Science",
  faculty_edu: "Faculty of Education",
  faculty_law: "Faculty of Law",
  faculty_med: "Faculty of Medicine",
  faculty_vet_sci: "Faculty of Veterenary Science",
  faculty_pharm_sci: "Faculty of Pharmaceutical Science",
  faculty_ahs: "Faculty of Allied Health Sciences",
  faculty_arch: "Faculty of Architecture",
  faculty_arts: "Faculty of Arts",
  faculty_eng: "Faculty of Engineering",
  school_pathumwan: "Pathumwan Demonstration School",
  school_triamudom: "Triam Udom Suksa School",
  school_satitchula_elementary: "CU Demonstration Elementary School",
  school_satitchula_secondary: "CU Demonstration Secondary School",
  chalerm_phao_junction: "Chalerm Phao Junction",
  lido: "Lido",
  chamchuri_9: "Chamchuri 9",
  chula_stadium: "Chula Stadium",
  dhamma_center: "Dhamma Center",
  bldg_witthayaphatthana: "Wittayaphattana Building",
  bts_national_stadium: "BTS National Stadium",
  chulapat_13: "Chulapat 13",
  chale: "Chalerm Rachakumari 60",
  student_dormitory: "Student Dormitory",
  office_university: "Office of the University",
  u_center: "U-Center",
  samyan_market: "Samyan Market",
  im_park: "I'm Park",
  cu_ihouse: "CU iHouse",
};